language: java
sudo: false
install: gradle -q assemble
script: gradle -i check
jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

env:
  global:
    - TERM=dumb
    - secure: "XzCjWbN5BM2ioZy+1GVcFuHVUwX8YHjuved7gZ0CAHp1pMyhPudzZqlLZ2ZWKv44sVS/ZM4ylwbO4JFGyJcobd5/CeP+iJpYPRGas4EYWIuA882K3NgBEn8smnaxy/PcrQwl9QVhnMrsVu8KrmB/dHwBphMyfAT65+2eiQbQWRk="

after_success:
#  - gradle jacocoRootReport # coveralls
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: puniverse:OsnbakHrYeTcLyalVgtUeI4F

